### ISSUE TITLE
Call to a member function getPosition() In

### ISSUE THREAD

**Issue by badrusalsyihab** [interactiv4/b-responsive#12]
Hey All 

When I'm Using to be error here is :

Fatal error: Call to a member function getPosition() on a non-object in C:\xampp\htdocs\magento\app\code\core\Mage\Page\Block\Template\Links.php on line 119

Please What Your Solution For my problem ..?

**Comment by magentogirl** [comment]
what version of magento are you using?

**Comment by Vinai** [comment]
In Magento versions older then 1.7 CE / 1.12 EE there is no way to remove the wishlist link with layout XML without breakage.
I suggest you upgrade Magento, or implement some other workaround customized for your version of Magento.

**Comment by badrusalsyihab** [comment]
Magento ver. 1.6.2.0 ..
Ok thanks Vinai I will try your recommendation..

**Comment by badrusalsyihab** [comment]
I will try Magento ver. 1.8.0.0 broken layout
