### ISSUE TITLE
Missing Files After Initial Installation

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#13]
After cloning the main repository, checking out the the CE branch, and installing into a fresh 1.8.1 system, there's a number of files (images, javascript) that fail to download on the main page.

These files should be included with the main package **or** if this is a bootstrap/sass thing some sort of installation guide/instructions should be added to the wiki. 

```
http://magento-bootstrap.dev/skin/frontend/base/default/images/logo.gif
http://magento-bootstrap.dev/skin/frontend/base/default/images/media/col_right_callout.jpg
http://magento-bootstrap.dev/skin/frontend/base/default/images/logo.gif
http://magento-bootstrap.dev/skin/frontend/base/default/images/media/col_right_callout.jpg
http://magento-bootstrap.dev/skin/frontend/enterprise/responsive/js/jquery-1.10.2.min.map
```

![screen shot 2013-12-16 at 7 47 44 pm](https://f.cloud.github.com/assets/184372/1761411/0b815dd8-66ce-11e3-9717-c8a0977ff731.png)

The end result of this on the homepage looks like this

![screen shot 2013-12-16 at 7 50 58 pm](https://f.cloud.github.com/assets/184372/1761434/7fd264ac-66ce-11e3-8da6-0b6248762fea.png)

and my theme configuration looks like this (package set to _enterprise_, theme set to _responsive_)

![screen shot 2013-12-16 at 7 54 59 pm](https://f.cloud.github.com/assets/184372/1761450/076385fe-66cf-11e3-8325-42ddbd9228b0.png)

**Comment by philwinkle** [comment]
I believe that the images are returning 404 because those are base images from the Magento EE sample data or the enterprise / default theme. 

As for the jquery.min.map I'll look into that more closely.

**Comment by astorm** [comment]
I'm not sure I'm clear on workflow here — should the `jquery-1.10.2.min.map` file be added to the ce-branch and not the master branch?
