### ISSUE TITLE
CE: Move to "default" Design Package?

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#19]
When I first checked out the ce-branch, I made the (incorrect) assumption I could just drop the theme into a new design package named enterprise, which led to errors. 

The CE version should be in the `default` design package OR a new unified design package should be created if you're trying to create a single theme for both.

**Comment by codethis** [comment]
Could be solved using solution in issue #50

**Comment by magentogirl** [comment]
We moved it to it's own package
b-responsive/default
and 
b-responsive/enterprise
