### ISSUE TITLE
CE: Header Layout is Broken

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#23]
When installing into the default theme on a Magento 1.8.1 system, the page header on the homepage has a broken layout. 

![screen shot 2013-12-17 at 12 48 56 pm](https://f.cloud.github.com/assets/184372/1768035/c38be04a-675c-11e3-980d-0516d1b6a8b1.png)

CE version needs either a new template and/or new CSS rules to fix this so it looks more like the version on http://responsive.redlightblinking.com/

![screen shot 2013-12-17 at 12 50 28 pm](https://f.cloud.github.com/assets/184372/1768045/e3f9f1fa-675c-11e3-9c9d-68d80d52680e.png)

This should be **new work** and not just a copy of the EE code (licensing, etc.)

**Comment by magentogirl** [comment]
Fixed
