### ISSUE TITLE
CE: Account Login Page

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#26]
After installing the theme in the `default` design package in Magento 1.8.1 CE, and navigating to the account login page

http://magento-1-8-1.dev/customer/account/login/

There's still some old base design package elements — specifically the orange text.

![screen shot 2013-12-17 at 1 50 00 pm](https://f.cloud.github.com/assets/184372/1768606/47d2eaf8-6765-11e3-87dd-e55618c6415f.png)

This should match the same page on the reference design: http://responsive.redlightblinking.com/customer/account/login/

![screen shot 2013-12-17 at 1 51 09 pm](https://f.cloud.github.com/assets/184372/1768610/63decdb6-6765-11e3-80db-96b1496c5186.png)

**Comment by magentogirl** [comment]
Fixed
