### ISSUE TITLE
CE: Create an Acount Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#27]
When installing the `response` theme into the `default` design package on a Magento 1.8.1 system, the Create an Account page still has old deisgn element

http://magento-1-8-1.dev/customer/account/create/

![screen shot 2013-12-17 at 1 55 01 pm](https://f.cloud.github.com/assets/184372/1768671/1a9288fe-6766-11e3-9957-a2cd1d20c913.png)

This should match the design reference at: http://responsive.redlightblinking.com/customer/account/create/

![screen shot 2013-12-17 at 1 57 18 pm](https://f.cloud.github.com/assets/184372/1768691/4532dfa0-6766-11e3-845b-a26d2a800279.png)

**Comment by magentogirl** [comment]
Fixed
