### ISSUE TITLE
CE: Alignment of Success Messages

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#28]
When installing the `response` theme into the `default` design package on a Magento 1.8.1 system, the alignment on the success messages is off

![screen shot 2013-12-17 at 1 59 35 pm](https://f.cloud.github.com/assets/184372/1768716/a53b5602-6766-11e3-97d1-e70bb18bb448.png)

The "Thank you" should not overlap with the icon.  You can reproduce this issue by
1. Navigating to http://magento.example.com/customer/account/create/
2. Entering information for a new account
3. Clicking on Submit

Expected Behavior: Green Success message looks good

Actual Behavior: Green Success message looks bad, with text and icon overlapping

**Comment by magentogirl** [comment]
Fixed
