### ISSUE TITLE
CE: Account Information Page has Old Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#29]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the Account information page has the old default theme background color, and the required fields text is still orange.

![screen shot 2013-12-17 at 2 04 29 pm](https://f.cloud.github.com/assets/184372/1768768/4cbdd9cc-6767-11e3-94dc-c55db6ce26ee.png)

Steps to Reproduce
1. Log into Magento with a customer account at http://responsive.redlightblinking.com/customer/account/login
2. Click on My Account at top of page
3. Click on Account Information link in left sidebar

Expected Behavior: Account Information layout and colors should match design reference: http://responsive.redlightblinking.com/customer/account/edit/

![screen shot 2013-12-17 at 2 07 37 pm](https://f.cloud.github.com/assets/184372/1768795/c47affbc-6767-11e3-8aea-7e9dd2ce5ab5.png)

Actual Behavior: Account Information layout and colors mix bootstrap and default design theme.

**Comment by magentogirl** [comment]
Fixed
