### ISSUE TITLE
CE: Customer Address Book Page has old Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#31]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the Address Book page has old design elements

![screen shot 2013-12-17 at 2 19 20 pm](https://f.cloud.github.com/assets/184372/1768883/4c4d4b1a-6769-11e3-99a5-930b1f945ddd.png)

Steps to Reproduce
1. Log into Magento with a customer account at http://responsive.redlightblinking.com/customer/account/login
2. Click on My Account at top of page
3. Click on Address Book link in left sidebar

Expected Behavior: Layout and colors should match design reference: http://responsive.redlightblinking.com/customer/address/new/

![screen shot 2013-12-17 at 2 20 24 pm](https://f.cloud.github.com/assets/184372/1768891/75d1e4be-6769-11e3-801a-6e8db1507a50.png)

Actual Behavior: Account Information layout and colors mix bootstrap and default design theme.

**Comment by magentogirl** [comment]
Fixed
