### ISSUE TITLE
CE: Newsletter Subscription Page has Old Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#32]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the Newsletter Subscription page has old design elements

![screen shot 2013-12-17 at 2 23 38 pm](https://f.cloud.github.com/assets/184372/1768924/e46a30c0-6769-11e3-977e-24f3deb9d013.png)

Steps to Reproduce
1. Log into Magento with a customer account at http://responsive.redlightblinking.com/customer/account/login
2. Click on My Account at top of page
3. Click on Newsletter Subscriptions link in left sidebar

**Expected Behavior**: Layout and colors should match design reference: http://responsive.redlightblinking.com/newsletter/manage/

![screen shot 2013-12-17 at 2 24 39 pm](https://f.cloud.github.com/assets/184372/1768939/0acd251a-676a-11e3-939b-f4ea2501c197.png)

**Actual Behavior**: Account Information layout and colors mix bootstrap and default design theme.

**Comment by magentogirl** [comment]
Fixed
