### ISSUE TITLE
Alignment on Sitemap Page

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#33]
The design elements (for both the EE and CE versions) on the folllowing page

http://responsive.redlightblinking.com/catalog/seo_sitemap/category/

is slightly askew (Products Sitemap, 32 item(s) text)

![screen shot 2013-12-17 at 2 27 01 pm](https://f.cloud.github.com/assets/184372/1768966/6773594c-676a-11e3-8454-215deee29ed5.png)

**Comment by magentogirl** [comment]
Fixed
