### ISSUE TITLE
CE: Advanced Search Page Contains Old Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#34]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the advanced search page contains old design elements

http://magento.example.com/catalogsearch/advanced/

![screen shot 2013-12-17 at 2 28 44 pm](https://f.cloud.github.com/assets/184372/1768977/9b5ee4d8-676a-11e3-8edd-139a1c024951.png)

This should match the design reference at: http://responsive.redlightblinking.com/catalogsearch/advanced/

![screen shot 2013-12-17 at 2 29 23 pm](https://f.cloud.github.com/assets/184372/1768983/b3603898-676a-11e3-88cc-74c539a2098b.png)

**Comment by magentogirl** [comment]
Fixed
