### ISSUE TITLE
CE: Contact Us page contains old Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#35]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the contact us page contains old design elements

http://magento-1-8-1.dev/contacts/

![screen shot 2013-12-17 at 2 30 16 pm](https://f.cloud.github.com/assets/184372/1768999/d336d348-676a-11e3-981f-f13c8d74afe3.png)

This should match the design reference at: http://responsive.redlightblinking.com/contacts/

![screen shot 2013-12-17 at 2 31 55 pm](https://f.cloud.github.com/assets/184372/1769011/104d94f6-676b-11e3-8b2a-b32be0c8ed33.png)

**Comment by magentogirl** [comment]
Fields are now too small
![screen shot 2014-03-21 at 4 54 10 pm](https://f.cloud.github.com/assets/1179278/2487866/fa32d536-b13a-11e3-8008-089b988c0ced.png)
