### ISSUE TITLE
CE: Question: Default Display of Multi-Column Layouts

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#36]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, many of the page default to the multi-column layout, and contain the same, ancient design elements we've been looking at for 6 years -- many of which don't fit in the columns

**Back to School**

![screen shot 2013-12-17 at 2 36 26 pm](https://f.cloud.github.com/assets/184372/1769043/b4d66cc8-676b-11e3-989e-598061140fc0.png)

**Did you Know Dog** 

![screen shot 2013-12-17 at 2 37 08 pm](https://f.cloud.github.com/assets/184372/1769048/d2f50d54-676b-11e3-93db-02f394a79457.png)

What steps need to be taken to ensure this isn't a user's first run experience with bootstrap for CE.

**Comment by mcmattgr** [comment]
Would adding the "img-responsive" class to the images fix that?  It would then fit the image to the container.

**Comment by astorm** [comment]
@mcmattgr That'd be a good fix for a specific site, but I'm not sure it's the best solution for a project meant to form the bedrock of a new site.  Ideally we want to
1. Remove those images completely
2. Have the CE theme and EE themes ship with as-near-as-possible identical layouts

**Comment by magentogirl** [comment]
These are gone. CE & EE are as-near-as-possible identical layouts
