### ISSUE TITLE
CE: Broken Image on Catalog Listing Page

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#37]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, there's a broken image on the catalog listing page.  You can see this by using a sample data installed system and navigating to either of the following URLs ( depends on your URL rewrite settings)

http://magento-1-8-1.dev/furniture.html
http://magento-1-8-1.dev/catalog/category/view/id/10

![screen shot 2013-12-17 at 2 45 57 pm](https://f.cloud.github.com/assets/184372/1769126/055056f4-676d-11e3-8688-b92b23a0841e.png)

The source for the image is

http://magento-1-8-1.dev/skin/frontend/base/default/images/sort_asc_arrow.gif

**Comment by magentogirl** [comment]
Fixed
