### ISSUE TITLE
CE: Layered Navigation Looks Wrong

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#38]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the layered navigation looks wrong.  

You can observe this in a system with the sample data installed, and browsing to one of the following URLs (depending on your rewrite settings)

http://magento.example.com/furniture.html
http://magento.example.com/catalog/category/view/id/10

![screen shot 2013-12-17 at 2 51 44 pm](https://f.cloud.github.com/assets/184372/1769180/0d64cbda-676e-11e3-8763-0d5792f7c1d2.png)

The style of the layered navigation elements should look like the reference design: http://responsive.redlightblinking.com/catalog/category/view/s/furniture/id/3/

![screen shot 2013-12-17 at 2 53 43 pm](https://f.cloud.github.com/assets/184372/1769188/255b416a-676e-11e3-82b2-ed078d28c622.png)

**Comment by magentogirl** [comment]
Fixed
