### ISSUE TITLE
CE: Add to Cart Success Message Layout is Broken

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#39]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the "Add to Cart" success message's layout is "off"

![screen shot 2013-12-17 at 5 16 46 pm](https://f.cloud.github.com/assets/184372/1770107/161e7924-6782-11e3-8f0f-0b21504e65ff.png)

Steps to Reproduce
1. Browse to a Catalog Listing page
2. Click on "Add to Cart" for any product

**Expected Behavior**: [Product was Added to Cart] Message appears next to success icon

**Actual Behavior**: [Product was Added to Cart] Message appears over success icon

**Comment by magentogirl** [comment]
Fixed (icons are gone?)
