### ISSUE TITLE
CE: One Page Checkout contains old design elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#40]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the one page checkout contains old design elements.

![screen shot 2013-12-17 at 5 21 00 pm](https://f.cloud.github.com/assets/184372/1770137/cee11dfe-6782-11e3-8e6a-9dd5329a0df7.png)

Steps to Reproduce
1. Add any item to your shopping cart
2. Browse to the cart listing page by clicking on the My Cart link in the top right corner
3. Click on green "Proceed to Checkout" button

**Expected Behavior**: Layout Matches reference design: http://responsive.redlightblinking.com/checkout/onepage/

![screen shot 2013-12-17 at 5 23 43 pm](https://f.cloud.github.com/assets/184372/1770154/76d61eb0-6783-11e3-9cba-e681a19c5794.png)

**Actual Behavior**: Layout contains old design elements

**Comment by magentogirl** [comment]
Fixed
