### ISSUE TITLE
CE: Multiple Address Checkout Contains Old Design Elements

### ISSUE THREAD

**Issue by astorm** [interactiv4/b-responsive#41]
When installing the `responsive` theme into the `default` design package on a Magento 1.8.1 system, the multi-address checkout contains old design elements.

![screen shot 2013-12-17 at 5 28 46 pm](https://f.cloud.github.com/assets/184372/1770165/e1afe928-6783-11e3-8e1b-03dbd9cf517f.png)

Steps to Reproduce
1. Add any item to your shopping cart
2. Browse to the cart listing page by clicking on the My Cart link in the top right corner
3. Click on green "Checkout with Multiple Addresses" link below green checout button
4. If not logged in, login or register an account

**Expected Behavior**: Layout matches reference design: 

![screen shot 2013-12-17 at 5 33 01 pm](https://f.cloud.github.com/assets/184372/1770173/654044e0-6784-11e3-9d1c-aabd8b8a5853.png)

**Actual Behavior**: Layout contains old design elements mixed with bootstrap elements.

**Comment by magentogirl** [comment]
Fixed
