### ISSUE TITLE
No Style sheet?

### ISSUE THREAD

**Issue by brentwpeterson** [interactiv4/b-responsive#44]
I think we are missing a style sheet?

![screen shot 2013-12-23 at 3 58 04 pm](https://f.cloud.github.com/assets/611893/1803476/42698492-6c1e-11e3-8b6f-4287bc4c69d9.png)

**Comment by magentogirl** [comment]
Seems it is trying to add skin/frontend/base/default/css/styles.css instead of skin/frontend/default/default/css/styles.css - this is related to #19

**Comment by maierb** [comment]
CE: 1.8.1
@brentwpeterson @magentogirl I copied skin/frontend/default/default/ to skin/frontend/b-responsive/default-core and then set that folder to be the theme default -> This solved the missing stylesheets. Now i just have /skin/frontend/b-responsive/default/images/bkg_block.gif still reporting a 404
This fixed a number of display issues i was seeing

![screenshot 2014-06-04 16 07 46](https://cloud.githubusercontent.com/assets/3238167/3179257/ee76b0a4-ec23-11e3-88d2-a6a45398de79.png)
