### ISSUE TITLE
Use enterprise theme fallback

### ISSUE THREAD

**Issue by codethis** [interactiv4/b-responsive#50]
This is more a preference thing but using a simple enterprise fallback module would allow for a cleaner theme structure, it would allow this theme to sit away from the core enterprise files so upgrading is easier. Been using this on all enterprise projects to allow this:

https://www.sonassi.com/knowledge-base/magento-kb/magento-enterprise-theme-fallback/

Let me know if this is something you want to feature, I'll add it in and do a pull request.

**Comment by magentogirl** [comment]
YES! We want this. We have installed Mark Shust's Enterprise Fallback on our other projects. Please send the pull request! Awesome!

We published the new package structure with b-responsive/default.

**Comment by philwinkle** [comment]
You don't need Mark's or Sonassi's module to do this - we should code one up that's specific for this project.

**Comment by codethis** [comment]
my preference was to use the Sonassi extension, what would be the benefit of coding our own surely the job is the same??
