### ISSUE TITLE
b-responsive should not set itself as the default theme

### ISSUE THREAD

**Issue by gordonknoppe** [interactiv4/b-responsive#52]
It seems a little heavy handed to me for a design theme to assume it's going to be used as the new default theme.  I would leave it as an exercise for the store owner to choose which website / store view they are going to use this theme for.

**Comment by maierb** [comment]
@gknoppe-guidance  I agree, this took me by surprise that my default package was automatically changed to b-responsive once I unzipped the theme. I had never seen this before, I would be curious to know how it works.
