### ISSUE TITLE
Home Theme is not like the Home Demo Theme

### ISSUE THREAD

**Issue by mateusneves** [interactiv4/b-responsive#66]
How i configure in the Magento for this theme home be like the home demo site: http://responsive.redlightblinking.com/

**Comment by fusco** [comment]
same here.

**Comment by danielc1234** [comment]
Agreed. This would be awesome to be able to have some data to make the download more like the demo. Not much information on how to manipulate the slider, megamenu, cms homepage, etc. etc.

**Comment by brcline** [comment]
How much detail is too much?

**Comment by danielc1234** [comment]
@brcline?? You lost me.

**Comment by magentogirl** [comment]
We've added an installer script to create the homepage. Documentation coming soon!
