### ISSUE TITLE
how to add images in mega menu

### ISSUE THREAD

**Issue by ManindraSingh** [interactiv4/b-responsive#67]
i'm newbie to megento i'm using your theme but unable to add image in mega menu dropdown just like your demo site.how can i achieve that?

Here is a link to my demo site:http://jewelsmiths.in/

**Comment by magentogirl** [comment]
You create a static block with the identifier megamenu_category_3 where 3 is the category id. (Find the category Id in manage Categories listed next to the name)

Then you can add html like this in the block (from the demo):

<pre><code>
     <div class="mega-block-right">
     <p><a href="#"><img class="img-thumbnail" src="http://placehold.it/200x150" alt="" /></a></p>
     <a class="btn btn-primary btn-block" href="#">Shop Now <span class="glyphicon glyphicon-chevron-right">&nbsp;</span></a>
     </div>
</code></pre>
