### ISSUE TITLE
Mega Menu? 

### ISSUE THREAD

**Issue by rubytastic** [interactiv4/b-responsive#78]
So this needs mega menu extension? 
Anyone could please post me to the correct link to install it ( its free? ) because the theme fails as is.

Also there are lots of small issues with this repo in the category not up2date. 
I will address most of these so if interested please let me know how to solve this problem and I will also contribute all my changes back. Kind regards

**Comment by rubytastic** [comment]
Found out one can disable mega menu from the system menu, 
is the megamenu referred to the payed one my magstore?

**Comment by rubytastic** [comment]
Even after disabling it still requires the files not existant.
Any way to add them fix this ?

**Comment by rubytastic** [comment]
Tried everything to remove the extension but it keeps trying to load it, even after logout of the admin and removing the MegaMenu.xml

Warning: include(Mage/Megamenu/Model/Category/Attribute/Source/Type/Style.php): failed to open stream: No such file or directory  in /srv/mysite.com.nl/httpdocs/lib/Varien/Autoload.php on line 94

#0 /srv/_customers/mysite.com.nl/httpdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(Mage/Me...', '/srv/_customers...', 94, Array)
#1 /srv/_customers/mysite.com.nl/httpdocs/lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('Mage_Megamenu_M...')
#3 [internal function]: spl_autoload_call('Mage_Megamenu_M...')
#4 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Config.php(1346): class_exists('Mage_Megamenu_M...')
#5 /srv/_customers/mysite.com.nl/httpdocs/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('megamenu/catego...', Array)
#6 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(383): Mage::getModel('megamenu/catego...')
#7 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(201): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#8 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Block/Catalog/Category/Tab/Attributes.php(113): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset))
#9 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Category_Tab_Attributes->_prepareForm()
#10 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#11 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Block/Catalog/Category/Tabs.php(140): Mage_Core_Block_Abstract->toHtml()
#12 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Catalog_Category_Tabs->_prepareLayout()
#13 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#14 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Block/Catalog/Category/Edit/Form.php(55): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'tabs')
#15 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Catalog_Category_Edit_Form->_prepareLayout()
#16 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#17 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form/Container.php(82): Mage_Core_Model_Layout->createBlock('adminhtml/catal...')
#18 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Widget_Form_Container->_prepareLayout()
#19 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#20 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'category.edit')
#21 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'category.edit')
#22 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#23 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#24 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#25 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#26 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#27 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Adminhtml/controllers/Catalog/CategoryController.php(201): Mage_Adminhtml_Controller_Action->loadLayout()
#28 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_CategoryController->editAction()
#29 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#30 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#31 /srv/_customers/mysite.com.nl/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#32 /srv/_customers/mysite.com.nl/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#33 /srv/_customers/mysite.com.nl/httpdocs/index.php(91): Mage::run('', 'store')
#34 {main}

Any help please?

**Comment by danielc1234** [comment]
Clear all your caches?

**Comment by rubytastic** [comment]
Yes tried that also, it seems to really miss some files from the mega menu ( the one I listed is not in the repo either ) and not honoring the disabled feature in the admin panel.
Just to make it clear; this is not needing any external extensions?  ( But then again even with disabled option it throws this error when you go to category management in the admin )

**Comment by danielc1234** [comment]
Even if you go to /etc/modules/  and find the xml file and edit to 'false'?

**Comment by rubytastic** [comment]
Daniel 
I even get this when I remove the module .xml completely.
I cannot pinpoint the issue, is anyone using b-responsive on there site without these problems?
Going to redownload and extract the official release version then.

**Comment by rubytastic** [comment]
I still have same issues with official release, zipped and extracted. 
Also there are several layout issues that are not visible in the demo website http://responsive.redlightblinking.com/

Shame, Is this repo the same version of code that runs that demo site? I would really love to make a big mayor contribution to the code. But with these issues its just costing me value time.

All caching and compiling is disabled in my Magento Development. I have cleared all the caches also.

**Comment by rubytastic** [comment]
Setting the magmenu to false throws another warning. 
Warning: include(Mage/Megamenu/Model/Category/Attribute/Source/Type/Style.php

**Comment by danielc1234** [comment]
Not sure what you are doing wrong. I just downloaded it and it worked as is. Maybe re-install magento? This could be a very good theme if there was more interest in it. Not a very active thread.

**Comment by rubytastic** [comment]
I also have styling issues Daniel.
I was planning to give this theme a mayor overhaul but sadly it seems the theme as-is as provided here is not the same version that is used on the demo website.

Could you please share with me your settings in the theme settings for Magento I might have it setup wrong there?
I only have current package name set to b-responsive and all other fields empty under, settings -> design. Is that correct? Will try to setup a new Magento also that is blank and see if things work there.

**Comment by rubytastic** [comment]
Im using Magento 1.9.1 CE btw, is that the same version you are using?

**Comment by danielc1234** [comment]
We are using 1.9.1 as well.
This is my settings in admin   http://screencast.com/t/bcu17q4qa

It is too bad the person handling this project does not take it more serious. This could have been an extremely good theme. 
Have you played with the magento theme rwd? That is magento's default responsive theme?

**Comment by rubytastic** [comment]
Same As I , you also used the released .zip version not the master code?

IF this works I plan to overhaul it totally. 
Do you have development / design background? We could refactor the existing theme together. 
I have some customer payed time to work on this, but its also a prestique project for me so I will be spending a little bit more time to get a really decent theme. Still I hate Magento;p

**Comment by danielc1234** [comment]
I sent you an email. Let me know.

**Comment by danielc1234** [comment]
rubytastic, I have some of the older versions that you can have. The one I am using seems to be working fine.

**Comment by rubytastic** [comment]
Other problems on a clean installation with the latest release, it just f**ks up magento more. Shame.
@danielc1234 
I don't use the e-mail on this account May I ask you to send it to another e-mail? I will try your version before really dishing this shame.

**Comment by danielc1234** [comment]
Sure, what is the email address?

**Comment by rubytastic** [comment]
can you send it to voorpascal@gmail.com ? I have tried all options, its a shame, just big waste of time. The current theme on a clean magento 1.9.1 CE messes up everything. The category editor breaks. The layout of the released version has several flaws. Perhaps it works correct on 1.8 but on 1.9 it just breaks everything, this theme seems to be the only option out there.

I will try your older version then, and see how that works out, perhaps I can revive it from there.

**Comment by danielc1234** [comment]
Just sent it.

**Comment by rubytastic** [comment]
Thank you Daniel, I let you know how it works out

**Comment by rubytastic** [comment]
Any news from the authors?

Anyone got b-repsonsive to work?
The current repo seems not having all files, any plans to add them so we can take a look on giving this repo some new live and activity?

**Comment by rubytastic** [comment]
In the end it bowled down to a local issue ::| 
Its working now and the theme is correct. 
I will be updating the theme with several fixes in the next 2 weeks.

**Comment by danielc1234** [comment]
@rubytastic Please post your changes. I'd like to see what you end up doing with it.

:)
